apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository  
metadata:
  name: gitops-app
  namespace: flux-system  
spec:
  interval: 1m 
  url: https://github.com/AungAung-Drlinuxer/gitops-lab1
  ref:
    branch: main 
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-app
  namespace: flux-system
spec:
  interval: 5m0s 
  path: ./app
  prune: true
  sourceRef: 
    kind: GitRepository
    name: gitops-app
  targetNamespace: gitops-app
